### ISSUE TITLE
Refactor Compute class for API V4

### ISSUE THREAD

**Issue by orrabin** [fog/fog-ovirt#14]
Opening this to track refactorings that came up in the review of the first V4 supporting version.

https://github.com/fog/fog-ovirt/pull/10#discussion_r179033858
https://github.com/fog/fog-ovirt/pull/10#discussion_r179035152

Add documentation for method: https://github.com/fog/fog-ovirt/pull/10#discussion_r179136501

**Comment by shiramax** [comment]
closing this issue since the PR got merged.
