### ISSUE TITLE
NameError: uninitialized constant Fog::JSON

### ISSUE THREAD

**Issue by lhellebr** [fog/fog-ovirt#19]
When using Foreman with Fog and Fog-oVirt (Create Host -> select oVirt -> OS -> Image Based), I get the attached traceback.
[tb.txt](https://github.com/fog/fog-ovirt/files/1947059/tb.txt)

**Comment by lhellebr** [comment]
Most likely, JSON should be required in both fog-ovirt and fog-core.

**Comment by lhellebr** [comment]
Related: https://github.com/fog/fog/issues/3993 , https://github.com/fog/fog-core/issues/234

**Comment by geemus** [comment]
I think this will likely be fixed by #20

**Comment by lhellebr** [comment]
Although the PR ^ is still not merged, I was unable to reproduce this today.

**Comment by shiramax** [comment]
The issue was fixed by: https://github.com/fog/fog-ovirt/pull/20

**Comment by geemus** [comment]
Sounds good, thanks!
