### ISSUE TITLE
Fix namespaces for fog-core 2 best practices

### ISSUE THREAD

**Issue by orrabin** [fog/fog-ovirt#54]
`fog-core` 2.1.1 added deprecation warnings that can be seen in the tests:  
```
[fog][DEPRECATION] Unable to load Fog::Ovirt::Compute
[fog][DEPRECATION] The format Fog::Compute::Ovirt is deprecated
```
According to the best practices here added by `fog-core` the namespaces need to change.

**Comment by shiramax** [comment]
@orrabin I think we can close this issue, correct?

**Comment by orrabin** [comment]
Yes, the PR was merged, I'm closing.
