### ISSUE TITLE
Accessing api to detect version is not working with 1.14 cluster

### ISSUE THREAD

**Issue by pkliczewski** [fog/fog-ovirt#66]
Cluster 1.14 is not yet supported but version detection code is not working. This needs to be fixed once we have Kubevirt release supporting this cluster level.

**Comment by shiramax** [comment]
closing this issue because it's related to fog-kubevirt and not fog-ovirt.

**Comment by pkliczewski** [comment]
This issue should be open for `fog-kubevirt` but now it is already fixed by [this](https://github.com/fog/fog-kubevirt/pull/137) PR.
